### ISSUE TITLE
Updating Rows

### ISSUE THREAD

**Issue by Assada** [dailyburn/bigquery#11]
How i can update some row in BigQuery?

**Comment by sturgill** [comment]
BigQuery is an immutable datastore. There is no way to modify data or delete a certain row once it's been written. Note these are constraints of the engine itself; not this library. 

If you need to modify data, BigQuery is not the right storage engine for your needs.

**Comment by Assada** [comment]
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language

'The BigQuery Data Manipulation Language (DML) enables you to update, insert, and delete data from your BigQuery tables.'

**Comment by sturgill** [comment]
Interesting. Looks like beta support was released in August 2016. We'll look into this, but it's not currently supported in this library. Thanks for bringing this up.

**Comment by Assada** [comment]
As temporary solution for updating i am wrote Update function:

```go

func (c *Client) Update(dataset, project, queryStr string) (*bigquery.QueryResponse, error) {
	var lSQL bool = false

	datasetRef := &bigquery.DatasetReference{
		DatasetId: dataset,
		ProjectId: project,
	}

	query := &bigquery.QueryRequest{
		DefaultDataset: datasetRef,
		MaxResults:     int64(100),
		Kind:           "json",
		Query:          queryStr,
		UseLegacySql:   &lSQL,
	}

	service, err := c.connect()

	var dataChan chan Data

	if err != nil {
		if dataChan != nil {
			dataChan <- Data{Err: err}
		}
		c.printDebug("updating error", err)
		return nil, err
	}

	qr, err := service.Jobs.Query(project, query).Do()

	return qr, err
}
```
